version: 2.1

aliases:
  - &okteto-login |
    curl https://get.okteto.com -sSfL | sh
    mkdir -p $HOME/.okteto
    touch $HOME/.okteto/.noanalytics
    okteto login ${OKTETO_URL} --token ${OKTETO_TOKEN}

jobs:
  release:
    docker:
      - image: okteto/golang-ci:1.17.5
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.6
      - run: *okteto-login
      - run:
          name: Build and Push Pipeline Installer Image
          command: |
            export INSTALLER_BASE_TAG=${CIRCLE_TAG}
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            make push
workflows:
  version: 2
  release:
    jobs:
      - release:
          context:
            - Okteto-Staging
            - dockerhub
          filters:
            branches:
              ignore: /.*/
            tags:
              only:
                - /^\d+\.\d+\.\d+$/