version: 2.1

jobs:
  release:
    docker:
      - image: cimg/base:latest
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.6
      - run:
          name: Build and Push Pipeline Installer Image
          command: |
            docker build -t okteto/installer-base:${CIRCLE_TAG} .
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push okteto/installer-base:${CIRCLE_TAG}
workflows:
  version: 2
  release:
    jobs:
      - release:
          context:
            - dockerhub
          filters:
            branches:
              ignore: /.*/
            tags:
              only:
                - /^\d+\.\d+\.\d+$/