version: 2.1

jobs:
  test:
    docker:
      - image: cimg/base:2022.03-20.04
    resource_class: medium
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.6
      - run: 
          name: Build image
          command: docker build -t okteto/pipeline-runner:test .
  release:
    docker:
      - image: cimg/base:2022.03-20.04
    resource_class: small
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.6
      - run:
          name: Build and Push Pipeline Installer Image
          command: |
            docker build -t okteto/pipeline-runner:${CIRCLE_TAG} .
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push okteto/pipeline-runner:${CIRCLE_TAG}
  release_latest:
    docker:
      - image: cimg/base:2022.03-20.04
    resource_class: medium
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.6
      - run:
          name: Build and Push Pipeline Installer Image
          command: |
            docker build -t okteto/pipeline-runner:latest .
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push okteto/pipeline-runner:latest
workflows:
  version: 2
  test:
    jobs:
      - test
  release:
    jobs:
      - release:
          context:
            - dockerhub
          filters:
            branches:
              ignore: /.*/
            tags:
              only:
                - /^\d+\.\d+\.\d+$/
  release_latest:
    jobs:
      - release_latest:
          context:
            - dockerhub
          filters:
            branches:
              only: main
