version: 2.1
alias:
  - &okteto-login |
    curl https://get.okteto.com -sSfL | sh
    mkdir -p $HOME/.okteto
    touch $HOME/.okteto/.noanalytics
    okteto context use ${OKTETO_URL} --token ${OKTETO_TOKEN}
  - &docker-login echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

jobs:
  build:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run: *okteto-login
      - run: 
          name: Build Rootful Image
          command: make build-rootful
      - run: 
          name: Build Rootless Image
          command: make build-rootless
  release:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run: *okteto-login
      - run: *docker-login
      - run:
          name: Build and Push Rootful Image
          command: make push-rootful
      - run:
          name: Build and Push Rootless Image
          command: make push-rootless

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: Product-okteto-dev
  release:
    jobs:
      - release:
          context:
            - dockerhub
            - Product-okteto-dev
          filters:
            branches:
              ignore: /.*/
            tags:
              only:
                - /^v\d+\.\d+\.\d+$/
